### ISSUE TITLE
NameError: name 'raw_input' is not defined 

### ISSUE THREAD

**Issue by vasantvaniya** [01010000-kumar/PhoneSploit#1]
Traceback (most recent call last):                                                                                                                                    
  File "phonesploit.py", line 841, in <module>                                                                                                                        
    main_linux()                                                                                                                                                      
  File "phonesploit.py", line 498, in main_linux                                                                                                                      
    device_name = raw_input (arrow+" phonesploit"+Fore.RED + "(connect_phone) "+Fore.WHITE + "> ")                                                                    
NameError: name 'raw_input' is not defined

**Comment by 01010000-kumar** [comment]
what operating system are you using?

**Comment by xcodz-dot** [comment]
@aerosol-can Is this repository compatible with Python3 because raw_input is only availabel in Python2 which has reached its end of support.
